# Generated by Django 5.0.3 on 2024-03-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suplementos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suplemento',
            name='imagen',
            field=models.ImageField(upload_to='imagenes/'),
        ),
    ]
