# Generated by Django 5.0.3 on 2024-03-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suplementos', '0004_alter_suplemento_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='suplemento',
            name='marca',
            field=models.CharField(default='test', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suplemento',
            name='size',
            field=models.CharField(default='test', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suplemento',
            name='imagen',
            field=models.ImageField(upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='suplemento',
            name='nombre',
            field=models.CharField(max_length=64),
        ),
    ]
