# Generated by Django 5.0.3 on 2024-03-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suplementos', '0005_suplemento_marca_suplemento_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suplemento',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
