# Generated by Django 5.0.3 on 2024-03-15 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suplementos', '0006_suplemento_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='suplemento',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='marca', to='suplementos.marca'),
        ),
    ]
